-- AlterTable
ALTER TABLE `user` MODIFY `image` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `pagesCount` INTEGER NOT NULL DEFAULT 0,
    MODIFY `hoursCount` INTEGER NOT NULL DEFAULT 0,
    MODIFY `wordsCount` INTEGER NOT NULL DEFAULT 0;
