-- AlterTable
ALTER TABLE `library` MODIFY `createdAt` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `readlist` MODIFY `createdAt` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `timeline` MODIFY `createdAt` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `user` MODIFY `createdAt` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `wishlist` MODIFY `createdAt` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
